train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  data_dir: "/kaggle/input/librispeech/train-clean-100"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  data_dir: "/kaggle/input/librispeech/dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  data_dir: "/kaggle/input/librispeech/test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
