train:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  data_dir: "/kaggle/input/librispeech/dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  data_dir: "/kaggle/input/librispeech/test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
