defaults:
  - model: conformer
  - metrics: example
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: example
  - transforms: example_only_instance
  - _self_
text_encoder:
  _target_: BeamSearchEncoder
  beam_size: 15
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "beam_search_proof" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/baseline/model_best.pth" # path to the pretrained model
