defaults:
  - model: conformer
  - writer: cometml_lm_with_aug
  - metrics: example
  - datasets: test_other
  - dataloader: example
  - transforms: allin
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-4
  pct_start: 0.01
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 10
  lm_name: "librispeech-3-gram"
trainer:
  log_step: 250
  n_epochs: 20
  epoch_len: 500
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: # if True, will override the previous run with the same name
  monitor: "min val_WER" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved_tuned"
  seed: 1
  from_pretrained: "models/model_best.pth"
